### PR TITLE
fall back to releaseUrl if snapshotUrl is empty

### PR DESCRIPTION
**Pull request by lukewink**
Fixes: https://github.com/bndtools/bnd/issues/1620
Signed-off-by: Luke Winkenbach <lukewink@gmail.com>

### CODE REVIEW

**Comment by bjhargrave** [comment]
If you need a snapshot repo to be always configured, then configure one.

**Comment by pkriens** [comment]
There are a number if situations why I need to be able to have this separate.

**Comment by lukewink** [comment]
I was making my changes based on the intended behavior written in Configuration.java.
    /**
     * The url to the remote snapshot repository. If this is not specified,
     * it falls back to the release repository or just local if this is also
     * not specified.
     */
    String snapshotUrl();

It doesn't appear that the current code falls back to the release repository which is why I made the change.

**Comment by bjhargrave** [comment]
I think the comments are out of date. They reflected an earlier intent during initial development of the maven repo support.

**Pull request closed without merging**
