### PR TITLE
[bnd] cli baseline - verbose API diff

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by timothyjward** [comment]
Does this need equivalent configuration/work to be available in the bnd-baseline-maven-plugin?

**Comment by bjhargrave** [comment]
> Does this need equivalent configuration/work to be available in the bnd-baseline-maven-plugin?

Well, this PR does the work all on the command line UI rather than in bndlib where gradle, maven and the command line can all use the changes.

**Comment by bjhargrave** [comment]
It is also possible the gradle and maven output is already this detailed and that the command line UI was behind. :-)

**Comment by rotty3000** [comment]
Well, many moons ago I proposed exactly this type of enhancement to the baseline "reporting". However it was rejected for reasons I don't remember. Let's merge this in and @timothyjward if you try it and like what you see then perhaps I could be convinced to elevate this directly up to the baseline engine.

The one major caveat is that right now each and every baseline "client" handles presentation pretty much how they choose. So that would have to be corrected to provide a more unified reporting model.

**Comment by bjhargrave** [comment]
I think each driver will need to control presentation. Maven/gradle will need to log to their logger and/or write a report to some file in the appropriate output folder. So I don't think we can push all of presentation down into bndlib.

**Comment by rotty3000** [comment]
Got it! Would it be an option is to make just the logic reusable?

**Pull request merged**
