### PR TITLE
Updated documentation of findproviders macro

### PR DESCRIPTION
**Pull request by glimmerveen**
Updated documentation of the newly added findproviders macro.

@pkriens : I was unsure about where to place the Maven part you suggested I add. If you had another place in mind, please let me know.

### CODE REVIEW

**Comment by rotty3000** [comment]
This looks really great @glimmerveen but could you add your `Signed-of-by:` attribute so we can accept it? (just sign off your commit and then force push to your branch is all you need to do)

**Comment by glimmerveen** [comment]
I updated my commit, is this what you had in mind @rotty3000 ?

**Comment by rotty3000** [comment]
haha, I do aplogize, it's correct including the typo I made in the attribute which I tried to quicky correct (however I don't think corrections in comments get email updates).

`Signed-off-by:` (note that I missed the second `f` earlier). Please update it one last time ;) and thanks again.

**Comment by glimmerveen** [comment]
Haha, I totally missed that typo :)

**Comment by bjhargrave** [comment]
Thanks!

**Pull request merged**
