### PR TITLE
fixes #1213

### LINKED ISSUE #1213: gradle non-workspace plugin does not process includes from manifest configuration
Given the following:
```gradle
jar {
    manifest {
        attributes('-include': 'other.bnd')
    }
}
```
where `other.bnd` exists "at the correct place", the directives contained within do not get processed.

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by bjhargrave** [comment]
This is not the right solution. There are also some larger issues here. 

The manifest is not a bnd file. It should be treated as a "prepend" to the bnd file. That is, anything in the bnd file will overwrite what is in the jar task manifest. This means that if the bnd file has a -include property, it must override the -include property in the jar task manifest. Your solution does not do this and will create a very different world than other bnd users have.

I am trying to think up a better solution.

**Comment by rotty3000** [comment]
I agree with the "prepend to the bnd file" idea. Didn't know how else to achieve it.

**Comment by rotty3000** [comment]
perhaps the setProperties methods in bnd should pull in any already set properties and then call the doInclude.

**Comment by bjhargrave** [comment]
Replaced by https://github.com/bndtools/bnd/pull/1215

**Comment by bjhargrave** [comment]
> perhaps the setProperties methods in Processor should pull in any already set properties (merging it's own passed properties last) and then call the doInclude().

This wouldn't work since you only want to process -include once you have all the properties loaded since later properties can override -include. And if setProperties can be called multiple times, you never know when the last call has been made to process -include. So the solution is to load the jar task manifest entries into a Properties object, add the bnd file entries over that (to allow overrides) and then setProperties on the final Properties object. This is the solution in #1215.

**Comment by rotty3000** [comment]
Thx!

**Comment by bjhargrave** [comment]
> Thx!

And thanks for finding the bugs!

**Pull request closed without merging**
