### PR TITLE
[reporter] Add default readme templates

### LINKED ISSUE #3161: [reporter] Add a default set of Templates into bnd (cli)
bnd should provide some default Templates to generate MD files.

Uses Command:
'exportreport exportmd'

@cdelg  would it be okay to take your templates as base? 
I would add some "easy to copy code fragments" e.g "configurator json" and fix some bugs 

see https://github.com/bndtools/bnd/pull/3152

- generate List-Entrys every time in same order

### PR DESCRIPTION
**Pull request by cdelg**
Closes #3161 

This based on the work of @stbischof in PR #3152. In complement I have added a set of updated templates (visit https://github.com/cdelg/bnd-doc-demo to see how they look) and some fixes on top of the initial implementation.

As I have reused code of @stbischof maybe we should wait before merging?  

Signed-off-by: Clement Delgrange <cl.delgrange@protonmail.com>

### CODE REVIEW

**Comment by bjhargrave** [comment]
> As I have reused code of @stbischof maybe we should wait before merging?

We would also need @stbischof Signed-off-by as well.

**Comment by cdelg** [comment]
> We would also need @stbischof Signed-off-by as well.

Can we have two Signed-off-by in a single commit? Can I add it for him?

**Comment by bjhargrave** [comment]
> Can we have two Signed-off-by in a single commit? 

Yes.

> Can I add it for him?

I think so, but it would be good for him to affirmatively agree to this in this PR via a comment.

**Comment by bjhargrave** [comment]
> it would be good for him to affirmatively agree to this in this PR via a comment.

Since @stbischof never put his Signed-off-by in #3152, he needs to indicate his Signed-off-by here.

**Comment by cdelg** [comment]
@bjhargrave  do you think the templates should be tested? (There is already some tests to check if the templates can be resolved).
If yes where should I put the test cases (reporter project, bnd, maven bnd plugin)?

Also the build hasn't completed yet, maybe it should be restarted.

**Comment by bjhargrave** [comment]
> do you think the templates should be tested? (There is already some tests to check if the templates can be resolved).

Ideally, yes.

> If yes where should I put the test cases (reporter project, bnd, maven bnd plugin)?

I would say the reporter project.

> 
> Also the build hasn't completed yet, maybe it should be restarted.

Travis is messed up at the moment. Many builds are failing due to some issue with Travis communicating with Maven Central.

**Comment by cdelg** [comment]
Where should I add documentation for this, in a new page at the top level?

**Comment by bjhargrave** [comment]
> Where should I add documentation for this, in a new page at the top level?

I assume under any existing reporter docs. If there isn't any, then a new chapter seems to make sense.

**Comment by cdelg** [comment]
WIP:

    Need more tests.
    Documentation.

**Comment by stbischof** [comment]
Hi and thank you @cdelg for finishing.

What is the best way to Sign-off?

**Comment by cdelg** [comment]
This PR can be reviewed now. I will made an other PR with a main chapter to document the generation of documentation. 

The templates are now tested. You can look at https://github.com/cdelg/bnd-doc-demo/tree/master/bnd-workspaces/max-workspace to see how the readme files look like, if you have any comment...

@stbischof I think you can close the other PR and I have added a  `Signed-off-by` in this commit for you.

**Comment by stbischof** [comment]
Hi,

I closed #3152.

I would like to add some more information to the template.
Should we do this in this  PR or an other PR?


- ReferenceBinding Information
- json snippet for Configurator
- json snippet for OSGI/Sling-Feature
- sourceCode snippet for ConfigAdmin
- ? sourceCose Snipped for AmdatuTesting ConfigurationStep (not sure)


Here is my first try. What do you think About?

```
{
{% for pid in c.configurationPid %}
/*
 * Component: {{ c.name }}
 * policy:    {{ c.configurationPolicy }}
 */
{% set pidOcd = "notset" -%}
{%- set factoryPidOcd = "notset" -%}
{%- for ocd in metatypes -%}
{%- if pid in ocd.pids -%}
{%- set pidOcd = ocd -%}
{%- elseif pid in ocd.factoryPids -%}
{%- set factoryPidOcd = ocd -%}
{%- endif -%}
{%- endfor -%}
{%- set o = "notset" -%}
{%- if pidOcd != 'notset' -%}
    "{{ pid }}":{
{%- set o = pidOcd -%}
{%- elseif factoryPidOcd != 'notset' -%}
    "{{ pid }}~FactoryNameChangeIt":{
{%- set o = factoryPidOcd -%}
{%- else -%}
    "{{ pid }}":{

{%- endif %}
        //# Reference bindings    
{%- if c.references is empty -%}
        // none
{%- endif %}            
{%- for r in c.references %}
        // "{{r.name}}.target": {% if r.target=='' %}"(objectClass=*)"{% else %}"{{r.target}}"{% endif -%}
{%- if loop.last -%}{%- if loop.parent.o == 'notset' %}{% else %},{% endif %}{% else %},{%- endif -%}
{%- endfor %}

        //# ObjectClassDefinition - Attributes
{%- if o == 'notset' %}
        //(No PidOcd available.)
{% else %}
{%- for a in o.attributes %}
		/*
		 * Required = {{a.required}}
         * Type = {{ this.printPropertyType(a.type,(a.cardinality != 0)) }}
{%- if not empty(a.description) %}
         * Description = {{ a.description }}
{%- endif %}
{%- if length(a.values) > 0 %}
         * Default = {{ this.printPropertyValues(a.type,a.values,(a.cardinality != 0)) }}
{%- endif %}
{%- if (not empty(a.max)) or (not empty(a.min)) %}
         * Value restriction = `min = {{a.min}}` / `max = {{a.max}}`
{%- elseif length(a.options) > 0 %}
         * Value restriction = {{ this.printOptions(a.options) }}
{%- endif %}
         */
        {% if a.required!='true' %}// {% endif -%}"{{ a.id }}": null {% if loop.last %}{% else%},{% endif %}
{% endfor %}
{%- endif -%}
{%- endfor %}

}

```

# RESULT:


​#### Configuration Template - Configurator

```
{

/*
 * Component: org.bipolis.common.builder.TestClass
 * policy:    optional
 */
"org.bipolis.common.builder.TestClass~FactoryNameChangeIt":{
        //# Reference bindings
        // "serializable.target": "(objectClass=*)",
        // "serializables.target": "(objectClass=*)",

        //# ObjectClassDefinition - Attributes
		/*
		 * Required = true
         * Type = String
         * Default = "myText"
         */
        "text": null ,

		/*
		 * Required = false
         * Type = String
         * Default = "myText"
         */
        // "text2": null ,

		/*
		 * Required = true
         * Type = String
         * Default = "myText"
         */
        "text3": null 


}
```



#### Configuration Template - Feature

```
TODO
```


#### Configuration Template - ConfigAdmin

```
TODO
```

**Comment by stbischof** [comment]
https://github.com/cdelg/bnd-doc-demo/tree/master/bnd-workspaces/max-workspace/org.domain.max

The references to the build artefacts redmeads does not work well. 

It references to itselfe

**Comment by cdelg** [comment]
> I would like to add some more information to the template.

All these configuration code snippets will make the file really long, no? More importantly, all these information will be there even if the user doesn't use any of these configuration mechanisms. An option could be the use of a template parameter which will make the snippets optional (and disabled by default)? 

> The references to the build artefacts redmeads does not work well.

The links open folders, this works fine in a multi-module maven project or from the Workspace to the projects. In the case of the `org.domain.max` project which has sub-bundles, the link target the same folder. The problem is that I don't know how the users will name their readme files, except if, in case of sub-bundles, we ask the user to name the subbundle readme files with a specific name (eg; readme.[bsn].md). What do you think?

**Comment by stbischof** [comment]
We should add some options to add additional snippets. This should be activated explicitly.

The references bindings of an component should be shown in a tablet without an option.
From my point of view, these are like optional configurations.
The use of the reference".target" is not really long described in the spec. But for me it is a impressive features!

But if it is more important for you to give a shot basic readme. Ist would be easier for me to add and use some additional options.


Concerning the readme_[bsn].md file for each subbundle I would prefere to have these fixes names for subbundles. So it is easier to follow the links to the page which describes the bundle.

**Comment by cdelg** [comment]
@stbischof if I resume your plan is to:
* Fix the links of sub-bundles project to target a readme file instead of the folder.
* Add a `References` subsection in the `Component` section to document component's references.
* Add a set of configuration snippets in subsections describing the PIDs/FactoryPIDs of components which must be explicitly activated thanks to template parameters.

@bjhargrave as you approved changes in this PR, should we treat those issues in other PRs?

**Comment by cdelg** [comment]
> Concerning the readme_[bsn].md file for each subbundle I would prefere to have these fixes names for subbundles.

We can do better than `readme.[bsn].md`, we can have `readme.[bsn - folderName].md`. For example, a project is named `org.max` that build two bundles with bsn `org.max.one.provider` and `org.max.two.provider`, in this case the readme should be named `readme.one.provider` and `readme.two.md` following the same convention as the `*.bnd` files.

@bjhargrave can I add this in the current PR?

**Comment by cdelg** [comment]
https://github.com/cdelg/bnd-doc-demo/tree/master/bnd-workspaces/max-workspace/org.domain.max is fixed, I could push the changes in this PR if it's fine for you?

**Comment by stbischof** [comment]
For me it would be fine, if you push the "sub-bundle link fix" to this PR.
This would be enough for this PR. Then we can do the additional Snippets in a separate PR.

**Comment by cdelg** [comment]
Et voilà

**Comment by bjhargrave** [comment]
Thanks for both of your contributions!

**Pull request merged**
