### PR TITLE
[bndtools debug] Overhaul debug source path generation

### LINKED ISSUE #3993: [bndtools debug] BndDependencySourceContainer to fully replace DefaultSourceContainer
`BndDependencySourceLookupDirector` is what populates the "source" tab in the debug launch configuration.

Currently, it adds two source containers - `DefaultSourceContainer` and `BndDependencySourceContainer`, in that order. The `DefaultSourceContainer` is the one used by the JDT core for Java projects. I am convinced that we should ideally not be using `DefaultSourceContainer` at all, as I will explain.

The JDT world assumes that the build path is identical to (or at the very least, a proper subset of) the run path. `DefaultSourceContainer` follows this assumption. Basically, it puts all of the build-time sources on the runtime source lookup path, including:

-The JRE you are building against
-The sources of any jars/libraries/projects in your dependencies
-The source of the project itself.

However, Bndtools launches are different - the run time dependencies are generally different (in fact, potentially completely different) from the build time ones. Some examples (both commonplace and more theoretical):
1. It is common (indeed, recommended by the good folk here) to build against osgi.core and then run against a particular implementation (eg, Felix or Equinox).
2. It is common to build against a lower version and then run against a higher version.
3. Using -runee it is possible to set a different JVM for runtime than what you used to build against.
4. It is even possible to create a bnd(run) launch within a project that doesn't actually include that project at all.

Having the wrong sources on the source lookup path at best uses extra computer resources and slows things down. At worst it makes debugging more difficult because it shows the wrong source. `DefaultSourceContainer` contributes to this by adding lots of the wrong sources.

At the very least, `DefaultSourceContainer` needs to be prioritized after the Bnd-specific dependencies. This would reduce the incidence of issues where the runtime versions are different (eg, the debugger will use the Felix source instead of the source from osgi.core). But ultimately, I think it would be best if `BndDependencySourceContainer` did a proper job of finding the sources for the *runtime* dependencies (including for the actual JVM that the `AbstractOSGiLaunchDelegate` chose to launch with, as opposed to the one that was built against), which would make `DefaultSourceContainer` redundant.

### PR DESCRIPTION
**Pull request by kriegfrj**
This commit significantly changes the layout of the source dependencies in the debug configuration window. I would be interested in hearing people's opinions and having them try it out to see if I've broken anything. See attached screenshot for an example:
BndDependencySourceContainer
Noteable features:

* `DefaultSourceContainer` is no longer used.
* `BndDependencySourceContainer` now contains a few intermediate nodes in its hierarchy to group the dependencies in a way that corresponds to the bnd(run) file - ie, separate entries for `runee`, `runfw`, `runpath` and `runbundles`
* `runpath` dependencies are now added too
* Bundle dependencies displayed as bundles using the Bndtools bundle icon
* `runee` is handled directly by `BndDependencySourceContainer` and will add
the sources for the VM that is actually used for launching (as opposed
to the one that was used for compilation).

Fixes #3993

### CODE REVIEW

**Comment by pkriens** [comment]
Wow, that looks eye watering! I wanna have it!

Is it ready to merge?

**Comment by kriegfrj** [comment]
> Wow, that looks eye watering good! I wanna have it!
> 
> Is it ready to merge?

Well, one thing I've learned in this is that source lookup in Eclipse is very complicated. Either i have not fully understood the need for this complexity, or else it is needlessly so...

Given the complexity, there's a chance i may have broken it in some obscure way (breakpint handling is one area to be wary of). So I'd feel uncomfortable about it finding its way in to 5.1 at this late stage, but I'd be fairly comfortable about inflicting it on us who can handle the bleeding edge so we can put it through its paces before the next release.

**Comment by kriegfrj** [comment]
The latest commit also fixes #3899 (downloading sources automatically). It was easier to add it to this PR as it depends on the new features implemented there.

**Comment by pkriens** [comment]
I think the current source code lookup is broken enough to not worry about some obscure bugs in this code. If we merge it today then we have at least 2 weeks to try it out. having source lookup of -runbundles would be an awesome feature to have in 5.1.

I am ok to merge this into 5.1.0 unless BJ explodes :-)

**Comment by bjhargrave** [comment]
> I am ok to merge this into 5.1.0 unless BJ explodes :-)

This code is way out of my area of knowledge! But lets give it a go...

**Comment by bjhargrave** [comment]
Thanks again for all your contributions, @kriegfrj!

**Comment by kriegfrj** [comment]
> This code is way out of my area of knowledge! But lets give it a go...

And here I was as a novice hoping that the experts would review it for me... 😆 Fingers crossed then...

**Comment by pkriens** [comment]
I am afraid, Fr. Krieg, that you've become the expert. And I got the distinct feeling there are not that many others in the world :-)

**Pull request merged**
