### PR TITLE
1504: BndEditModel does not handle -runblacklist

### PR DESCRIPTION
**Pull request by lostiniceland**
Task-Url: [bnd#1504](https://github.com/bndtools/bnd/issues/1504)

adding runblacklist to the known_properties will fire the corresponding
PropertyChangeEvent which is needed to fix [issue 1397](https://github.com/bndtools/bndtools/issues/1397) in BndTools.

### CODE REVIEW

**Comment by pkriens** [comment]
You miss the sign-off ...

**Comment by lostiniceland** [comment]
Sorry. I changed the commit (rebase) but its not showing here. Do I have to close this PR and create a new one?

**Comment by pkriens** [comment]
No, I have no idea how it works but once there is a PR it keeps tracking what you do in your repo ... magic.

**Comment by lostiniceland** [comment]
I have to create a new PR. This PR points to a commit-id which was replaced by a rebase

**Pull request closed without merging**
