### PR TITLE
bndtools: Fixup model properties for resolving

### PR DESCRIPTION
**Pull request by bjhargrave**
The model properties are not properly resolved for the special here
`${.}` macro. So make a copy and call replaceHere on the copy.

Fixes https://github.com/bndtools/bnd/issues/4396

### CODE REVIEW

**Comment by pkriens** [comment]
Should the code to fixup `${.}` to the owning file not be part of the BndEditModel? To fixup on the place where you use it means we have the same bug everywhere we use the BndEditoModel properties.

**Comment by bjhargrave** [comment]
> Should the code to fixup `${.}` to the owning file not be part of the BndEditModel?

I guess BndEditModel would need a getProperties method which resolved the `${.}` here macro since you would not want it resolved in the underlying properties of the model which would be written back to the file being edited. But I am not super familiar with BndEditModel, so I would need to leave such an improvement to you.

> To fixup on the place where you use it means we have the same bug everywhere we use the BndEditoModel properties.

How many other places do you think there would be? It would need to be something which uses the properties to then possible mutate the properties like resolving does.

**Comment by pkriens** [comment]
The purpose of the bndedit model is to keep the changes from the file. Every bit of GUI works from this.

As far as I can see, you can just move the code change you did for the RunResolution into the properties you get from the BndEditModel. I do not think there is anyone that would have a problem with fixed up `${.}`, on the contrary. Not doing this can create very subtle bugs like this one.

As far as I can see, the -runbundles update has to go to the BndEditModel and not the file. So you can return a copy from getProperties(), as you do in your fix.

**Comment by bjhargrave** [comment]
OK, I moved the here macro resolution into BndEditModel.getProperties. See https://github.com/bndtools/bnd/pull/4426

**Pull request merged**
