### PR TITLE
Update 305-startlevels.md - fix 404 link

### PR DESCRIPTION
**Pull request by chrisrueger**
I found some broken links in the documentation and trying to fix.

### CODE REVIEW

**Comment by chrisrueger** [comment]
@pkriens Question:

There is a broken link to `/releases/4.0.0/contact.html` in the footer of all older releases pages. I think it could be fixed with something like this:

image

Is this something which should be done? I have the fix ready using a regex search&replace. But it touches almost 5000 files. 
Or should older relase files stay untouched? 

Another question:
On https://bnd.bndtools.org/releases/4.3.0/chapters/250-resolving.html there is a broken link to [/qs/050-start.html](https://bnd.bndtools.org/qs/050-start.html)

Do you know which could be the correct target url?

**Comment by pkriens** [comment]
I do not think we should update the files in `docs/releases`. They are a snapshot copy for archival reasons. Some broken links are to be expected.

**Comment by pkriens** [comment]
Can you make sure you sign the commit with your email? I cannot merge it without

**Comment by chrisrueger** [comment]
> Can you make sure you sign the commit with your email? I cannot merge it without

Done

**Comment by kriegfrj** [comment]
Thanks @chrisrueger !

**Pull request merged**
