### PR TITLE
baseline: Use MavenBndRepository support for macros

### PR DESCRIPTION
**Pull request by bjhargrave**
We centralize the baseline version to a Workspace property.

### CODE REVIEW

**Comment by pkriens** [comment]
I guess this requires everybody to update their bndtools?

**Comment by bjhargrave** [comment]
> I guess this requires everybody to update their bndtools?

Yes if they are building Bnd. Like many other times in the past when we use new features added to Bnd. Eating our own food...

**Comment by pkriens** [comment]
Might be nice to get a warning on Slack or mailing list this is happening. It can take some time before you figure this out.

**Comment by bjhargrave** [comment]
Sure, I haven't merged this PR yet. But, in the past when such changes have happened, I have mentioned it on slack.

**Pull request merged**
