### PR TITLE
#3431 Support for SplashHandler in BND Launcher

### PR DESCRIPTION
**Pull request by juergen-albert**
Commit for #3431 
Signed-off-by: Juergen Albert <j.albert@data-in-motion.biz>

### CODE REVIEW

**Comment by pkriens** [comment]
I'd rather not have a specific splash handler. The intention of the launcher is that the embedded activators do this. Embedded activators are on the run path.

A valid concern is that they are not run until after all bundles are installed (start happens after). In a recent discussion, a large setup took 2.5 seconds so I do not think that is a real problem. However, a change that also allows embedded activators to run before install is ok with me. Currently the before/after start flag (static boolean IMMEDIATE) could be turned into a String or so to support multiple possibilities.

Another alternative is to add code to the launcher and change the main class.  See #3410

**Comment by bjhargrave** [comment]
> I'd rather not have a specific splash handler.

I agree. I am not excited by this PR as it currently stands. It is too specific and should be handled by a more generic means such as @pkriens suggests.

**Comment by juergen-albert** [comment]
I see your points. The whole eclipse start process is kind of special and it took me a while to solve a lot of their idiosyncrasies. The splashscreen and JNI part that handles this, however is something, I can't really change without touching the binary launcher. I still need to speak to Tom to find out, why this is entangled as it is. 

I hope that by offering a Eclipse capable export and Launcher, to get more people moving from PDE to BND. I hope that this helps us, to get more Eclipse Projects to produce better OSGi Bundles. Unfortunately, we/I have to make a few concessions in order to make it work, without changing things in to many eclipse core projects.

As an alternative suggestion, I'd like to make the create Framework Method protected. With this, my Launcher can inherit from the bnd Launcher and can do what I need to do without maintaining a copy of the Launcher.

@pkriens I've create a new Ticket for the Embedded Activator, because this would solve a few other issues for the eclipse start process.

**Comment by pkriens** [comment]
I do not want (as should be clear from the other discussion) make Launcher API. As said, I am ok to make it possible to start the Embedded Activators a bit earlier (although I would find a 2.5-sec delay acceptable.) 

If there are other functions missing let us discuss them here as well. Making launcher API will let everybody go in its own direction and forces the launcher to stay compatible. I think the launcher is powerful enough, or can be extended in a generic way, to solve most problems.

**Comment by juergen-albert** [comment]
Okay, to boil my problem down a bit:

Ehe equinox launcher executables that eclipse uses basically do bit of magic. They get a couple of properties (found e.g. in the eclipse.ini). At first it locates the jvm native library (e.g. the jvm.dll).  They take the jar mentioned as -startup, look for a main class declaration, instantiating it reflectively by calling the jvms native methods and call a run method with the arguments from the ini. 
In Eclipse pendant to the EmbeddedLauncher is in a separate jar. Before starting anything, it identifies the another native library and where to find the splashscreen. It then initializes its JNIBridge with the native library and displays the splash screen. this is then wrapped in a runnable (run removes the splash) and hands it over to the EclipseStarter (This is basically our Launcher), which then does the registering of the runnable in the framework and a lot more. 
For some reason, the native launcher calls in the JVM after the start of the first MainClass and expects to find the org.eclipse.equinox.launcher.JNIBridge class and wants to know about the native splash library location. If this class is not in the initial launch jar, a NoClassDef Exception is printed.
All 3 of their start components are together like 5k LOC. 

I want to get rid of as much non OSGi behaviour as possible and only cater to the few things that are really necessary to get eclipse running and exported with BND. Thus my solution looks at the moment as follows:

I have a pre launcher jar, which basically has something like the Embedded Launcher inside it. It additionally has the org.eclipse.equinox.launcher.JNIBridge the executable requires. It handles the splash and calls my Launcher similar to the bnd embedded launcher, but hands over the runnable. My Launcher itself looks exactly as the one in the PR. 

In addition to that I have a Launcher Plugin, that uses my pre launcher, so a splash can be shown, when started via bnd(tools). Additionally it overrides the executable method and can build something  that looks like an eclipse product export and does not use the f***ed up start mechanism of eclipse.

**Comment by pkriens** [comment]
What cannot be handled with Embedded Activators? (If necessary with before install activation)

**Comment by juergen-albert** [comment]
It might work with before install activation. I will implemente this and try it afterwards.

**Comment by bjhargrave** [comment]
I think we can close this since it is replaced by #3449, right?

**Comment by juergen-albert** [comment]
Yes, we can close this. The splash even works with the embedded activator

**Pull request closed without merging**
