### PR TITLE
comm.tests: Use different port range for windows

### PR DESCRIPTION
**Pull request by bjhargrave**
We were having intermittent BindException because the chosen port was in
use.

### CODE REVIEW

**Comment by pkriens** [comment]
Should we move this to aQute.lib? I did something similar last week and noticed there are some ranges that are free. Would be nice to have this knowledge central

**Comment by bjhargrave** [comment]
Well this is a hack. If we do anything in IO, we should make sure to return an available ephemeral port not just the next number in some range. And the free range for windows depends on the version of windows. https://support.microsoft.com/en-us/help/832017/service-overview-and-network-port-requirements-for-windows. The change I  made here works because Azure uses Windows Server 2016 to run the CI build for WIndows.

https://github.com/bndtools/bnd/blob/b4b07aff36c858b859a761e4ec0ea1222ad63e02/azure-pipelines.yml#L76

**Comment by pkriens** [comment]
It is better to have a hack in one place than in many places? 

This was exactly the same place that I fixed in the pkriens/beforelaunch branch.

**Comment by bjhargrave** [comment]
I guess it would have been nice if you had released this little fix by itself earlier :-) Would have saved everyone a lot of time.

**Pull request merged**
