### PR TITLE
[quickfix] Quickfix enhancements

### PR DESCRIPTION
**Pull request by kriegfrj**
* Improved support for quickfix in new situations (#4195).
* Reinstated some support for static imports that got broken in the new implementation.
* Implemented a facade so that the quick fix processor can be dynamically re-installed without restarting the workbench (#4227).

### CODE REVIEW

**Comment by kriegfrj** [comment]
Latest push removes one commit that has been superseded by #4229

**Comment by kriegfrj** [comment]
Test failure seems to be a bit of flakiness in `BuildpathQuickFixProcessorTest`. That needs investigation but it's a separate issue.

**Comment by pkriens** [comment]
I am ok to go ahead with this approach for now. Lets have a discussion just before 5.2 to see how it works out.

**Comment by bjhargrave** [comment]
@kriegfrj Please go ahead and rebase this and fix the merge conflict. Then we can merge for 5.2.

**Comment by kriegfrj** [comment]
> I am ok to go ahead with this approach for now. Lets have a discussion just before 5.2 to see how it works out.

If you're planning to have this discussion at a Bndtools meeting, if you give me 24 hours notice I can try and arrange to be on the call.

**Comment by kriegfrj** [comment]
> @kriegfrj Please go ahead and rebase this and fix the merge conflict. Then we can merge for 5.2.

Done! Now I can make a PR for the other enhancements I've added in the meantime. :smile:

**Pull request merged**
