### PR TITLE
Remove maven-compat dependency

### LINKED ISSUE #5042: Maven Plugins: Remove dependency on deprecated maven-compat
To reduce the download footprint and to get rid of using deprecated classes (also for making this compatible with the upcoming Maven 4) the plugin should not depend on the deprecated maven-compat artifact (compare with https://issues.apache.org/jira/browse/MNG-7266? and https://cwiki.apache.org/confluence/display/MAVEN/Plugin+migration+to+Maven3+dependencies) but use Resolver/Aether API directly.

### PR DESCRIPTION
**Pull request by kwin**
It is not longer in use
This closes #5042

### CODE REVIEW

**Comment by kriegfrj** [comment]
> It is not longer in use This closes #5042

Your sign-off is missing in the commit message. You need to run `git commit --amend -s` and then force-push.

**Comment by bjhargrave** [comment]
You need to amend your commits so that each commit message includes a `Signed-off-by` as required by CONTRIBUTING. Then push force your updated commits. Thanks.

**Comment by kwin** [comment]
@bjhargrave Done

**Comment by bjhargrave** [comment]
Thanks

**Pull request merged**
