### PR TITLE
native_capability support for Windows 10

### PR DESCRIPTION
**Pull request by seanbright**
Signed-off-by: Sean Bright <sean@malleable.com>

### CODE REVIEW

**Comment by bjhargrave** [comment]
cloudbees is acting weird. The builds cannot access cloudbees to download the gradle plugin. We'll have to restart the test builds later when cloudbees is happy again.

**Comment by seanbright** [comment]
I've prodded it a few times and it still looks wonky. Let me know when it's fixed and I will push again.

**Comment by bjhargrave** [comment]
You don't need to repush. We can restart the builds from the travis and appveyor websites. I just restarted them and they both were able to download the gradle plugin. So the issue with cloudbees seems to be resolved.

**Comment by seanbright** [comment]
Even better. Thanks.

**Pull request merged**
