### PR TITLE
workspace: Utilize workspace ReentrantReadWriteLock for locking

### PR DESCRIPTION
**Pull request by bjhargrave**
We replace the use of Bndtools' bndLock with the Workspace's
ReentrantReadWriteLock. This allows us to use read locking in most
places and write locking only when necessary.

### CODE REVIEW

**Comment by kriegfrj** [comment]
This PR is related to #4575?

**Comment by pkriens** [comment]
Hmm, shouldn't we have an agreement on where we do the locking? I am not sure it should be the responsibility of the bndlib to do its locking itself since in many cases you can guarantee the concurrency issues from outside. 

Not sure this is the right way to go.

**Comment by chrisrueger** [comment]
From 6ef310ec44697cd815697c1b0db51f074e6fe5b9
> We fix the remaining watcher
> to properly refresh the workspace in a job rather than on the main
> thread.

Could that reduce e.g. some UI-Freezes during a (longer) build? At the moment when a build caused by a changed file, typing e.g. in Java-Code editor becomes unresponsive / sluggish. I assume because some thing happening in the main thread. Would this change affect this somehow?

**Comment by bjhargrave** [comment]
> This PR is related to #4575?

Perhaps tangentially. I was trying to fix a nagging issue the quickfix tests would occasionally service and I wanted to use a read/write lock since we don't need exclusive locks in most places.



> Hmm, shouldn't we have an agreement on where we do the locking? I am not sure it should be the responsibility of the bndlib to do its locking itself since in many cases you can guarantee the concurrency issues from outside.

We should certainly discuss this. But by putting the burden on the caller, we make sure new bugs are always introduced as code is changed/added as the caller forgets to do locking or does it wrong. By having it in bndlib, the code is just-thread-safe.

> Could that reduce e.g. some UI-Freezes during a (longer) build?

I don't think so since  build wont be modifying the workspace properties files which is what triggers the refresh action.

**Comment by kriegfrj** [comment]
Did you consider a stamped lock instead of reentrant re-write lock?

**Comment by bjhargrave** [comment]
> Did you consider a stamped lock instead of reentrant re-write lock?

StampedLocks are not reentrant which is I think rather important in this case.

**Pull request merged**
