### PR TITLE
[Reporter] Add a Gogo report entry plugin

### PR DESCRIPTION
**Pull request by cdelg**
This PR is based on the work of @stbischof, it adds an entry plugin to report Gogo commands. The embedded readme template file will render the Gogo commands (as a man linux page).

Tests and doc are include in this PR, @stbischof don't hesitate to comment on this since it is based on your work with some fixes and changes.

Signed-off-by: Stefan Bischof <stbischof@bipolis.org> Clément Delgrange <cl.delgrange@protonmail.com>

### CODE REVIEW

**Comment by cdelg** [comment]
DCO is not happy with the double signed-off-by, someone knows the syntax?

**Comment by rotty3000** [comment]
```
Signed-off-by: Stefan Bischof stbischof@bipolis.org
Signed-off-by: Clément Delgrange cl.delgrange@protonmail.com
```

**Comment by bjhargrave** [comment]
@rotty3000 was missing the angle brackets around the email addresses. I have editing his comment to correct this.

**Comment by bjhargrave** [comment]
Thanks

**Comment by stbischof** [comment]
Thanks @cdelg !!!

**Pull request merged**
