### PR TITLE
[gradle] run task, runs a resolved bndrun file

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@bjhargrave please let me know what you think of this!

- the resolve task writes back it's changes (if successful) to the bndrun file being resolved
- the run task runs the specified bndrun file (you can debug using the runvm properties if needed)

**Comment by bjhargrave** [comment]
I am going to defer reviewing this till after 3.3.

**Comment by rotty3000** [comment]
I've been using these tasks for a couple days now with no adverse effects and I would like to merge into master if no one objects.

**Comment by bjhargrave** [comment]
Yes, I object. This is for 3.4.

**Comment by rotty3000** [comment]
Ok, I misunderstood. I thought that 3.3 was branched and master was "next".

**Comment by bjhargrave** [comment]
Well we have a number of changes now in master I think I want to merge into next for RC2. Was thinking of making an RC2 before I leave on a trip today.

**Comment by rotty3000** [comment]
Ok, that sounds reasonable!

**Comment by rotty3000** [comment]
Done!

**Pull request merged**
