### PR TITLE
Fix #937: @RequireCapability with 'value' attribute generates spuriou…

### LINKED ISSUE #937: @RequireCapability with 'value' attribute generates spurious entry
Define an annotation as follows:

    @RequireCapability(ns = "nsy", effective = "active", filter = "(foo=bar)")
    public @interface AnnotationWithValue {
	    String value();
    }

And use it on a component as follows:

    @AnnotationWithValue("hello")

The resulting `Require-Capability` header is:

    Require-Capability:
        nsy; value=hello; filter:="(foo=bar)"; effective:=active,
        hello; value=hello; filter:="(foo=bar)"; effective:=active

The first line with the `nsy` namespace is expected but the `hello` namespace is incorrect.

### PR DESCRIPTION
**Pull request by njbartlett**
@pkriens Please review, especially the removal of lines 308-310 of `AnnotationHeaders.java`, which were the direct cause of the bug. I don't understand why those lines were there in the first place, maybe you can recall the reason you wrote them.

### CODE REVIEW

**Comment by pkriens** [comment]
The purpose of the value attribute was to allow the Require/Provide capability to just set the remainder of the clause, unchecked. I.e. this would allow directives and other tricks that the standard syntax does not allow. I guess this is ok for the Require/Provide Capability itself but should not be used for the meta annotations ...

Not sure if we should kill this feature for the Require/Provide Capability annotation itself?

**Comment by njbartlett** [comment]
Okay I'm not sure I understand the difference between putting this on the user-defined annotation or the meta-annotation. However, if the feature exists at all it should at least work, i.e. not create random unsatisfiable requirements in the bundle...

**Comment by pkriens** [comment]
Why would it create random unsatisfiable requirements? The value was just suffixed after the namespace so the author could do whatever he wanted, e.g. if you wanted to use a directive?

**Comment by pkriens** [comment]
But I am ok to move that behavior to another named attribute though

**Comment by njbartlett** [comment]
"Why would it create random unsatisfiable requirements?"

Umm... because there's a bug!

**Comment by pkriens** [comment]
Why does RequireCapability(ns="foo", value="bar:=12") generate a bug?

You have not indicated (at least I do not see it) what the bug is that you're trying to solve? I assume(d) the bug is that if the meta annotation has 'value' you get shit. So I proposed to ONLY use the 'value' method from the RequireCapability annotation for this purpose. The annotated annotation's 'value' method should not leak upwards.

**Comment by njbartlett** [comment]
Okay seems we've been talking at cross purposes. Yes I'm fine with that solution, as long as it's compatible with the use-case I want to implement in #938

**Comment by pkriens** [comment]
So why not change the name of the value property used for the concatenation and then resubmit? The value property is not right anyway since you cannot really use it standalone anyway

**Comment by njbartlett** [comment]
`value` can be used standalone... it's a "magic" name in the Java language:

    @MyAnnotation("hello")

is equivalent to

    @MyAnnotation(value = "hello")

**Comment by pkriens** [comment]
Yes, so I suggested to rename the 'value' property in the  RequireCapability annotation to something like 'extra' so that it does not clash with this use.

**Comment by njbartlett** [comment]
Ah okay. Yes that sounds good.

**Pull request merged**
