### PR TITLE
fixes #1231

### LINKED ISSUE #1231: bnd cannot "automatically" resolve exported packages properly from WABs
When attempting to use the auto calculation of exported packages; i.e.

`-exportcontents: ${packages;ANNOTATED;org.osgi.annotation.versioning.Version}`

I discovered that bnd does not properly *learn* packages which are not rooted in the based of the jar. This is because the *prefix* resolved for classes rooted in a non-`.` Bundle-ClassPath is ignored completely.

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ok, I mixed the resources for two test cases together.. that was a bad idea. Fixing.

**Comment by rotty3000** [comment]
hmm still issues apparently... investigating.

**Comment by rotty3000** [comment]
@bjhargrave @pkriens thoughts?

**Comment by bjhargrave** [comment]
I need some time to get to this... trying to finish some other things...

**Comment by pkriens** [comment]
Looks ok to me ... nice work actually, this really was a bug.

Some hints:
a) Every Analyzer implements Domain so you can use setIncludeResource("...") instead of using  the ugly constants. Most OSGi headers and many bnd instructions are methods in there. Feel free to add missing methods/headers.
b) After you've done the build(), you can call `b.getExports().get("test.refer_versioned").getVersion()`. This is a lot smaller and cleaner then parsing the manifest

**Comment by rotty3000** [comment]
If you want I'll cleanup the test then merge?

**Comment by pkriens** [comment]
Yup, go ahead

**Pull request merged**
