### PR TITLE
fixes #3045 bnd launcher doesn't support framework extensions on Java 9+

### LINKED ISSUE #3045: bnd launcher doesn't support framework extensions on Java 9+
```
[1f-a299a1de9ee9] ERROR Events.Framework.org.eclipse.osgi:? - FrameworkEvent ERROR
org.osgi.framework.BundleException: Cannot support framework extension bundles without a public addURL(URL) method on the framework class loader: org.apache.aries.spifly.dynamic.framework.extension_1.2.0 [6]
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent0(FrameworkExtensionInstaller.java:119)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent(FrameworkExtensionInstaller.java:94)
	at org.eclipse.osgi.internal.loader.SystemBundleLoader$SystemModuleClassLoader.loadFragments(SystemBundleLoader.java:134)
	at org.eclipse.osgi.internal.loader.SystemBundleLoader.loadClassLoaderFragments(SystemBundleLoader.java:116)
	at org.eclipse.osgi.internal.loader.BundleLoader.loadFragments(BundleLoader.java:309)
	at org.eclipse.osgi.container.ModuleWiring.loadFragments(ModuleWiring.java:276)
	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:835)
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:551)
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:494)
	at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1129)
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1510)
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
```

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Hey @pkriens @bjhargrave this makes it possible for all of testing, launching to work with Java versions through Java 11 at least (with support for framework extensions, which was broken).

**Comment by rotty3000** [comment]
@pkriens I know you're busy. I'm wondering if, when you have a moment, you could check why the LauncherTest.testAgent (the only failing test) is failing? I tried to figure out what it was but there are some complex mechanics at work and I'm not really sure I get what's going on in this test. Thx

**Comment by rotty3000** [comment]
.. nevermind, I figure it out.

**Comment by pkriens** [comment]
I guess this needs then also to be done in biz.aQute.remote? It also does some classloader wizardry

**Comment by pkriens** [comment]
Maybe move the Modifiable Class loader to lib?

**Comment by rotty3000** [comment]
resent in https://github.com/bndtools/bnd/pull/3080

**Pull request closed without merging**
