### PR TITLE
[doc] commandline - merge the 2 doc pages 400 and 860

### PR DESCRIPTION
**Pull request by stbischof**
**Status**
- [ ] IN DEVELOPMENT
- [x] READY
- [ ] HOLD

**Description**
The doc pages chapters/400-commandline and 860-commands have the same content.
i merged it.

**Checklist**
- [ ] You have added unit tests
- [x] Documentation
- [x] squash your commits in separate `git rebase -i` and `git push -f`
- [x] Tag commit-message [exporter,wab,cli,libg,...]
- [x] Sign your work `Signed-off-by: Joe Smith <joe.smith@email.com>` or use `git commit -s`
- [ ] Related Spec: none
- [ ] Reference Issues: Fixes # 
- [ ] Backward compatibility conflicts:
 * none
- [ ] Known open Issues:
 * none

**Questions**

is there a way to see a preview of this site before merge?

### CODE REVIEW

**Comment by djencks** [comment]
Is this from a template? There’s a typo,
> squash your commits in seperate
Separate

David Jencks

**Comment by bjhargrave** [comment]
> Is this from a template? There’s a typo,
> > squash your commits in seperate
>
> Separate

Yes. A proposed template. See #2684 and comment.

**Comment by stbischof** [comment]
@djencks thank you! i changed it in the pull request.

**Comment by stbischof** [comment]
updated

**Comment by bjhargrave** [comment]
Thanks.

**Pull request merged**
