### PR TITLE
[reporter] Add commonInfo plugin for projects

### LINKED ISSUE #3291: [reporter] Add commonInfo plugin for projects
As for the workspace, common info on project will be useful in case of sub builder. Templates can then rely on this to document the "aggregator" project.

### PR DESCRIPTION
**Pull request by cdelg**
See #3291

This PR contains implementation, tests, and docs.

Closes #3291

Signed-off-by: Clément Delgrange <cl.delgrange@protonmail.com>

### CODE REVIEW

**Comment by cdelg** [comment]
WIP:
* Need more tests.
* Documentation.

**Comment by bjhargrave** [comment]
Can you please rebase on the tip of master? I just did a large cleanup/reformat of all the code in the repo.

**Comment by cdelg** [comment]
Rebased.

**Comment by bjhargrave** [comment]
Thanks!

**Pull request merged**
