### PR TITLE
[repo] Make some fields protected in OSGiRepository

### PR DESCRIPTION
**Pull request by psoreide**
Signed-off-by: PK Søreide <per.kristian.soreide@gmail.com>

### CODE REVIEW

**Comment by bjhargrave** [comment]
What is the point of this change? Subclasses can figure this out on their own.

**Comment by psoreide** [comment]
A lot of subclasses extend FixedIndexedRepo / AbstractIndexedRepo where these fields are protected. So to simplify transition to OSGiRepository I thought this was a good idea.

**Comment by bjhargrave** [comment]
But they would be better of overriding setRegistry/setReporter rather than making the fields API.

**Comment by bjhargrave** [comment]
Whenever one makes fields API, it makes thing much harder to reason about correctness and concurrency.

**Comment by psoreide** [comment]
OK, I'm closing this.

**Pull request closed without merging**
