### PR TITLE
disable test for JDK >=21

### LINKED ISSUE #6261: ClazzTest.testJiniPlatformClasses fails on Java 22
When building bndtools from source, the ClazzTest.testJiniPlatformClasses fails on Java 22. The same test passes with Java 17.

```
java.util.zip.ZipException: The JAR/ZIP file (.../git/bnd/biz.aQute.bndlib.tests/jar/jsk-platform.jar) seems corrupted, error: Invalid CEN header (invalid zip64 extra data field size)
	at aQute.bnd.osgi.Jar.buildFromZip(Jar.java:311)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:137)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:235)
	at aQute.bnd.osgi.Analyzer.addClasspath(Analyzer.java:2595)
	at test.ClazzTest.testJiniPlatformClasses(ClazzTest.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1827)
	at java.base/java.util.zip.ZipFile$Source.checkZip64ExtraFieldValues(ZipFile.java:1356)
	at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1316)
	at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1234)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1766)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1541)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:194)
	at aQute.bnd.osgi.Jar.buildFromZip(Jar.java:300)
	... 85 more


```

### PR DESCRIPTION
**Pull request by chrisrueger**
Closes #6261 

@reckart could you verify?

### CODE REVIEW

**Comment by chrisrueger** [comment]
Failing test seems to be flaky (`org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:59423'.`)

I retry later again

**Comment by reckart** [comment]
Interestingly, I get this now:

> * What went wrong:
Could not open settings generic class cache for settings file '.../git/bnd/settings.gradle' (.../.gradle/caches/8.1.1/scripts/cu3p7h8xrg0vd0273sq1t9m96).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

**Comment by reckart** [comment]
I don't think the failure is related to the changes. I believe that gradle itself may be incompatible with recent Java versions (I guess [gradle 8.1.1](https://docs.gradle.org/8.1.1/release-notes.html) can do up to Java 20). However, I neither changed my Java version or my grade installation since the last build where the test fail. I am not a gradle expert, but I wonder how could the build "run" at the time up to the failing test and how can it now suddenly fail due to class version issues?

**Comment by reckart** [comment]
My system gradle version is 4.8.1, but when I build bnd, I see a 8.1.1 version in the path (I assume that is the gradle version used by bnd)...

**Comment by chrisrueger** [comment]
> I see a 8.1.1 version in the path (I assume that is the gradle version used by bnd)...

Seems to be [this](https://github.com/bndtools/bnd/commit/f8cb22204b637ed81c8b69ec799bbffaf972a5ef#diff-5a1176f3fe2333d819d0fe19d4b52666cf6ba5bccad99aef169d3498ae023335)

**Comment by chrisrueger** [comment]
> * BUG! exception in phase 'semantic analysis' in source unit

Maybe gradlle caching stuff like [this](https://stackoverflow.com/a/53509014) ? 

Anyway since the build here runs ok now since we disabled the windows build [temporarily](https://github.com/bndtools/bnd/pull/6275). 

Let me know how your Java 22 build turns out. Regarding to gradle and Java version support I found this: https://docs.gradle.org/current/userguide/compatibility.html

But I guess upgrading bnd build to support JDK 22, it should probably addressed in a separate issue / PR. Maybe this could be a pointer: https://github.com/bndtools/bnd/pull/5707/files

@pkriens @bjhargrave

**Comment by reckart** [comment]
I have tried adding lines for Java 21 and 22 in the `TestHelper.groovy` so more recent Gradle versions are returned. However, when I run `./gradlew clean build`, it still seems to choose 8.1.1. What else needs to be done to bump the gradle version?

**Comment by chrisrueger** [comment]
@reckart try running additionally:

`gradle wrapper --gradle-version 8.10` in bnd project root

This should update the gradle wrapper to the specific gradle version.
The do the build command.

Note this will change some files which could be pushed to git. But I don't know if this should be done in this PR. Not sure what the others think about upgrading gradle.  But at least it would be good if you could do this locally and check if it works. If it works you could propose another PR.

**Comment by reckart** [comment]
Build runs through after updating the gradle wrapper as you suggested. Looks good.

**Comment by reckart** [comment]
Mind I still need to disable the `EphemeralPortTest` to avoid it failing with *address already in use**.

**Comment by chrisrueger** [comment]
> Build runs through after updating the gradle wrapper as you suggested. Looks good.

@pkriens what do you think? Should we upgrade the gradle wrapper in this PR too?

**Comment by chrisrueger** [comment]
@reckart I merged this as it is. There was no decision from the team to upgrade gradle wrapper in this too at this point. But since you were able to do that locally and build , I hope that is sufficient for you. 
I added a small section about upgrading the gradle wrapper to higher version in [CONTRIBUTING.md](https://github.com/bndtools/bnd/blob/master/CONTRIBUTING.md#gradle-wrapper).

**Comment by pkriens** [comment]
@chrisrueger I defer to you, don't see any harm

**Comment by chrisrueger** [comment]
> I defer to you, don't see any harm

Ok, I might create a new PR for bumping gradle wrapper to a higher version.

**Pull request merged**
