### PR TITLE
[repositories view] process refresh in normal job instead of workspace job

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by bjhargrave** [comment]
> I am not sure what you are trying to accomplish.

I can see that this is for https://github.com/bndtools/bnd/issues/4100.

But I think my other comments still apply.

**Comment by gamerson** [comment]
> It seems a WorkspaceJob is nice since it defers any builds until the job is done. Using a regular job means builds could start while we are processing the refresh.

If we use a workspace job, we must ensure that we will be able to get the Central.getWorkspace() without blocking.  We should try to avoid having a "UI" feature like this both hold a workspace lock and then potentially "block" for the Central.getWorkspace() that is the cause of the deadlock I was able to see in #4100 


If there a method that will try to "get" the Central.getWorkspace without blocking?  If so, we coudl do something like this

1. start a workspace job
2. nonblocking get() of workspace, if we get the workspace, then do our work
3. if we can't get the workspace without a block, then just end the workspace job and reschedule another one for a second later.

**Comment by bjhargrave** [comment]
Isn't the answer to do "onWorkspace(ws -> run WorkspaceJob)"? Then you defer the job until there is a workspace and the job is a workspace job.

**Comment by gamerson** [comment]
> Isn't the answer to do "onWorkspace(ws -> run WorkspaceJob)"? Then you defer the job until there is a workspace and the job is a workspace job.

I will try that.

**Pull request merged**
