### PR TITLE
Add parameter to skip bundle version check

### LINKED ISSUE #3446: Baseline - allow skipping exported package versions check and bundle version checks individually
We are in the process of migrating a large numble of bundles to using the `bnd-maven-plugin` and the `bnd-baseline-maven-plugin` instead of the `maven-bundle-plugin`. One part which is a bit of a bump in the process is that the baselining functionality now fails in case the expected bundle version was not changed.

This is a problem for us since we use a different versioning conventions:

- development releases are always odd
- release versions are always even

We recently had a case where a change was made, and the baseline correctly flagged the bundle version as needing a version bump from 1.2.6 to 1.3.0. However, we do not do this at development time, so we would need to change to 1.3.1-SNAPSHOT and then release at 1.3.2, which is confusing for consumers - where is 1.3.0 ?

Our workflow could be best adapted by allowing to control baselining for exported package versions and bundle versions.

### PR DESCRIPTION
**Pull request by kwin**
This closes #3446

### CODE REVIEW

**Comment by kwin** [comment]
Ok, I will try to come up with something...

**Comment by kwin** [comment]
@bjhargrave Actually `-diffignore: Bundle-Version` works already as expected. I just added some tests for that and clarified the documentation in the bnd-baseline-maven-plugin.

**Comment by bjhargrave** [comment]
Thanks for following up on this. We both learned how to disable bundle version checks. In hindsight, it seems sort of obvious :-)

**Comment by saumya1singh** [comment]
Hi, how can we use this param in a maven command? @bjhargrave @kwin 
maybe something like `mvn clean install deploy -diffignore`
I know that's wrong format

**Comment by bjhargrave** [comment]
> how can we use this param in a maven command?

You cannot with version 5.2.0. At your suggestion I just add properties to 6.2.0 with https://github.com/bndtools/bnd/pull/5051.

So once 6.2.0 releases (probably mid-Feb), you could say:

```
mvn clean install deploy -Dbnd.baseline.diffignores=Bundle-Version
```

**Comment by saumya1singh** [comment]
sounds great. thanks @bjhargrave 👍🏻

**Pull request merged**
