### PR TITLE
[remote agent] index a remote framework

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@pkriens how's this instead?

**Comment by pkriens** [comment]
Well, same problem? Why not do it as the distro command does? It gets the bundle revisions from the remote and then indexes it into a single manifest. Seems trivial to adapt this to create an index?

And why not use the distro jar? Seems easier to manipulate in the bndrun file then another indexed plugin?

**Comment by rotty3000** [comment]
the distro jar loses a lot of information! It removes all the resource capabilities!

**Comment by rotty3000** [comment]
It loses all of osgi.wiring.bundle, and osgi.wiring.host so that you can't resolve fragments against it.

**Pull request merged**
