### PR TITLE
Added mill-osgi plugin to tools documentation

### PR DESCRIPTION
**Pull request by lefou**

### CODE REVIEW

**Comment by lefou** [comment]
Ping

**Comment by lefou** [comment]
Ping. 

The bnd website states the following: 

> If you’re a developer of a tool that needs to be listed here, do not hesitate to submit a pull request at github.

I can't understand, why I received not even a small comment, what's wrong with this PR.

@pkriens , @bjhargrave , anyone?

**Comment by bjhargrave** [comment]
I was waiting on Peter to review/merge.

**Comment by pkriens** [comment]
We generally review these in a bi-weekly meeting but due to my 10 week schedule of travel I missed the last few.

**Comment by lefou** [comment]
Thanks for your feedback.

**Comment by lefou** [comment]
Just some feedback: I was searching for this contribution in the commit list and then in the contributors list, and in neither my name popped up. I think, you should merge future pull request by retaining their original authors. This is very well supported by git (it differentiates between author and committer).

**Pull request merged**
