### PR TITLE
A Requirement without a filter always matches.

### LINKED ISSUE #1687: IllegalStateException during Resolution without any cause
Resolving a workspace which worked previously fails with the lates DEV-build (3.3.0.DEV-20160908-141802-g8c80800) with the following message.

> java.lang.IllegalStateException: What?!? The capability was not found associated with any key! That is not possible at this stage.

The only bundle I know of which uses the require-capability model in this workspace is Pax-CDI  (1.0.0.RC1). Pax-CDI provides a extender-capability. 

test-workspace will follow. Unfortunately, no further information is available (error-log)

[bnd-1687.zip](https://github.com/bndtools/bnd/files/463873/bnd-1687.zip)

### PR DESCRIPTION
**Pull request by seanbright**
Fixes #1687

Signed-off-by: Sean Bright <sean.bright@gmail.com>

### CODE REVIEW

**Comment by seanbright** [comment]
Unit test to follow

**Comment by bjhargrave** [comment]
LGTM

**Comment by bjhargrave** [comment]
Add a test to verify that a requirement with no filter in a different namespace than the cap does not match.

**Comment by seanbright** [comment]
You are correct. Looks like all of the current call sites for the method already know that the namespaces match. I've added a check and a unit test.

**Comment by bjhargrave** [comment]
LGTM
-- 
-- 
BJ

**Pull request merged**
