### PR TITLE
Addition of target filtering in DSTestWiring

### PR DESCRIPTION
**Pull request by dleangen**
Thanks for introducing me to this great tool!

I noticed that there seems to be lack of support for the target filter for @References. I thought that I would use this PR as a means of getting a dialogue started around this feature. :-)

### CODE REVIEW

**Comment by bjhargrave** [comment]
Perhaps you should start with just an issue where you describe the problem you are having.

I am unclear what problem you are having here.

**Comment by dleangen** [comment]
Thanks, BJ.

[Issue created](https://github.com/bndtools/bnd/issues/1421).

**Comment by bjhargrave** [comment]
Perhaps we can close this PR?

**Comment by dleangen** [comment]
Yes, indeed. The discussion is happening in [the related issue](https://github.com/bndtools/bnd/issues/1421) as you suggested.

By the way, I didn't realize until know how much effort you are investing in keeping all this stuff lean and mean. It is a very time-consuming and thankless job. Thanks so much for all your efforts! :-)

**Pull request closed without merging**
