### PR TITLE
Bndrun refresh

### PR DESCRIPTION
**Pull request by bjhargrave**
Change ProjectLauncher.update to call getProject().refresh() and make FileSetRepository implement Refreshable. Also cleaned up code in FileSetRepository.

### CODE REVIEW

**Comment by pkriens** [comment]
Did you miss OSGiRunLaunchDelegate for a reason? There is also a refresh + update call in there?

**Comment by pkriens** [comment]
Overall looks good to me.

**Comment by bjhargrave** [comment]
> Did you miss OSGiRunLaunchDelegate for a reason? There is also a refresh + update call in there?

That code:

https://github.com/bndtools/bnd/blob/ff43712bc034e339f3aa17e5966a4db8d8b7d3de/bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java#L312-L314

did not call Processor.refresh(). It called other methods which do slightly different things. So I was afraid to remove these additional calls as I was not sure of the effect.

**Comment by pkriens** [comment]
Think we should also remove them and then see what happens

**Comment by pkriens** [comment]
It sucks we have no bndtools tests :-(

**Comment by bjhargrave** [comment]
> Think we should also remove them and then see what happens

Done in https://github.com/bndtools/bnd/pull/3297.

**Comment by kriegfrj** [comment]
> Think we should also remove them and then see what happens

I think this may have caused #3360.

**Pull request merged**
