### PR TITLE
Improve Resolve failed message and make it more helpful

### PR DESCRIPTION
**Pull request by chrisrueger**
Attempt to produce a more readable message from a failed Resolution instead of just "Resolution failed!"

New sentence reads:

> Resolution failed! You are missing a dependency containing the package / capability: "some.other.missing.package" (in version [2.3.0,3.0.0)). This is required by my.package.foo version=1.0.0).

Feel free to suggest better / different wording. But my goal was to make it an english sentence. 
I even thought about adding something like "e.g. search on google for `'some.other.missing.package jar'` and add that to your repository).

## Examples:

I tested it by removing some libraries on purpose from `central.maven` (then click on refresh Repositories) and then click "Resolve". This caused a previously successful resolution to fail.

image

image

This is just a first draft. If there is an agreement that this is helpful there is cleanup needed.
Feedback welcome.

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
from a user experience point of view, this is definitely useful!

**Comment by pkriens** [comment]
You have to put in some disclaimer. It often is true that the first part of the message shows the issue but the resolver is a deep tree that is tried and backtracked. Sometimes the top message is just the last branch it tried but the valid solutions are in a completely different branch.

I also think any efforts here should not be focused on the UI. If there is a way to improve the readability of the message, we should do this in the RunResolution so it can easily be shared by other drivers like bnd, gradle, etc.

**Comment by chrisrueger** [comment]
> You have to put in some disclaimer. It often is true that the first part of the message shows the issue but the resolver is a deep tree that is tried and backtracked. Sometimes the top message is just the last branch it tried but the valid solutions are in a completely different branch.

Ok, sure. any suggestions for wording? 
What about: 

Resolution failed! You **may** miss a dependency containing the package / capability: "some.other.missing.package" (in version [2.3.0,3.0.0)). This is required by my.package.foo version=1.0.0). Disclaimer: In some cases this is not the complete reason for resolution failure. Please check the resolution output below for more hints. 


> I also think any efforts here should not be focused on the UI. If there is a way to improve the readability of the message, we should do this in the RunResolution so it can easily be shared by other drivers like bnd, gradle, etc.

I will check what I can do there. Yes this was my main goal, to _somehow_ "translate" this nested tree into something readable. 

Thanks for the feedback.

**Comment by pkriens** [comment]
Man, you're on a roll! :-)

I've got lots more ideas!

**Comment by chrisrueger** [comment]
Update:

- the hint is now _prepended_ in ResolveProcess.format() if we got something. Otherwise it is the existing message. This can be refined by more heuristics as we identify them. I hope that is also consumed by other parts like maven / gradle .... haven't tested this yet.
- The UI now only contains some 

> guidance and kind of an example "how to read" the thing below.

image

I also experimented with adding the sentence from the UI to the message below, but then it looked redundant.

**Comment by pkriens** [comment]
You might want to try a number of times asking Chat GPT and how it structures it answer. Just paste the tree and look at how it makes it easier to explain.

There is also a class FilterParser that can 'simplify' the filter output. It takes a filter, parses it, and transforms it into something you'd see in the manifest. This is a much more readable format. You could first show the tree transformed with this output but we should also add the existing one since it contains a bit more information.

**Comment by chrisrueger** [comment]
> FilterParser that can 'simplify' the filter output

Oh this tip was gold 🎉 😄 

I took this advice to create a summary by putting a few words before and after each different type of Expression of the FilterParser so that the tree reads like a sentence. 

The full output is below with all the details.

image

All resolve Test still pass:
image


Here is the console output of the Test `/biz.aQute.resolve/test/biz/aQute/resolve/ResolveProcessTest.java` which shows how it looks in some other cases. 

```
Resolution failed. Summary:
      ⇒ because package: aQute.lib.io is not provided by any other bundle or dependency

Note: The summary above may be incomplete. Please check the full output below for more hints.
Capabilities satisfying the following requirements could not be found:

    [<<INITIAL>>]
      ⇒ osgi.wiring.package: (osgi.wiring.package=aQute.lib.io)
Resolution failed. Summary:
      ⇒ Service: objectClass=java.util.concurrent.Executor cannot be resolved

Note: The summary above may be incomplete. Please check the full output below for more hints.
Capabilities satisfying the following requirements could not be found:

    [<<INITIAL>>]
      ⇒ osgi.service: (objectClass=java.util.concurrent.Executor)
Resolution failed. Summary:
      ⇒ osgi.enroute.endpoint: &(osgi.enroute.endpoint=/sse/1)(version=[1.1.0,2.0.0)) cannot be resolved

Note: The summary above may be incomplete. Please check the full output below for more hints.
Capabilities satisfying the following requirements could not be found:

    [<<INITIAL>>]
      ⇒ osgi.enroute.endpoint: (&(osgi.enroute.endpoint=/sse/1)(&(version>=1.1.0)(!(version>=2.0.0))))
Resolution failed. Summary:
      ⇒ Bundle: biz.aQute.bnd cannot be resolved
              ⇒ because package: org.apache.tools.ant.types is not provided by any other bundle or dependency

Note: The summary above may be incomplete. Please check the full output below for more hints.
Capabilities satisfying the following requirements could not be found:

    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=biz.aQute.bnd)
          ⇒ [biz.aQute.bnd version=1.51.1]
              ⇒ osgi.wiring.package: (osgi.wiring.package=org.apache.tools.ant.types)
The following requirements are optional:
    [org.osgi.impl.bundle.bindex version=2.2.0]
      ⇒ osgi.wiring.package: (osgi.wiring.package=org.apache.tools.ant)
      ⇒ osgi.wiring.package: (osgi.wiring.package=org.apache.tools.ant.types)
    [biz.aQute.bnd version=1.51.1]
      ⇒ osgi.wiring.package: (osgi.wiring.package=org.apache.tools.ant)
    [osgi.enterprise version=4.2.0.201003190513]
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.persistence)
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.servlet.http)
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.servlet)
    [osgi.cmpn version=4.3.1.201210102024]
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.persistence)
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.servlet.http)
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.microedition.io)
      ⇒ osgi.wiring.package: (osgi.wiring.package=javax.servlet)
Resolution failed. Summary:
      ⇒ Bundle: biz.aQute.bnd cannot be resolved
              ⇒ because package: org.apache.tools.ant.types is not provided by any other bundle or dependency

Note: The summary above may be incomplete. Please check the full output below for more hints.
Capabilities satisfying the following requirements could not be found:

    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=biz.aQute.bnd)
          ⇒ [biz.aQute.bnd version=1.51.1]
              ⇒ osgi.wiring.package: (osgi.wiring.package=org.apache.tools.ant.types)

```

**Comment by pkriens** [comment]
Ready to merge?

**Comment by chrisrueger** [comment]
> Ready to merge?

Now yes. I did some cleanup.
FYI
I modified the package-related sentence:

**from:** `because package: org.apache.tools.ant.types is not provided by any other bundle or dependency`
**to:** `because Import-Package requirement for: org.apache.tools.ant.types could not be provided by any available bundle or dependency`

I hope this sentence more accurately describes the situation in OSGi-terms.

I adjusted the ResolveProcessTest output above.

**Comment by pkriens** [comment]
great, will merge when the build finishes. 

Looking for other things to do? I always thought an editor for the MavenBndRepository index file (mvn) would be great! It is basically a line oriented file with GAV's. We support macros, comments, and empty lines but the format is very easy. If we had an editor, we could add all the command line functions from aQute.bnd.main.MbrCommand. This would allow people to do quick updates of versions, add dependencies, etc.

(I keep asking until you say no 8-) )

**Comment by chrisrueger** [comment]
> great, will merge when the build finishes.

Thanks for the merge. Hope others will find that useful too. 

> 
> Looking for other things to do? I always thought an editor for the MavenBndRepository index file (mvn) would be great! It is basically a line oriented file with GAV's. We support macros, comments, and empty lines but the format is very easy. If we had an editor, we could add all the command line functions from aQute.bnd.main.MbrCommand. This would allow people to do quick updates of versions, add dependencies, etc.
> 
> (I keep asking until you say no 8-) )

Thanks for suggesting this. For the moment I would say politely no :) 
I'll probably do some documentation related PRs e.g. to document my recent additions (Repository Copy to clipboard, and the new wording of this PR). 

Depending on how time allows I try to pick some topics here and there  as I discover them during my daily work with bndtools. Usually things "I wish they could exist" are my motivation. And now, since I made first steps in the code base, I think this is easier now. 

But sure, maybe I might pick up the Editor topic. One button which could be great there would be this [Finding unused dependency in repository](https://bnd.discourse.group/t/finding-unused-dependency-in-repository/338)

I try to attend the Zoom calls and we can talk about stuff.

**Comment by pkriens** [comment]
> But sure, maybe I might pick up the Editor topic. One button which could be great there would be this [Finding unused dependency in repository](https://bnd.discourse.group/t/finding-unused-dependency-in-repository/338)

Yes, there are many other workspace wide functions applicable there. Maybe I should spend a day getting a rough editor in place. It is always a bit sad that a simple editor tends to be pretty hard in Eclipse.

Anyway, thanks for all your work!

**Comment by kriegfrj** [comment]
A quick note: after I merged this PR into my local repo, whenever I tried to run a resolve inside the test Eclipse instance, I was getting a `MethodNotFoundException` for the newly-added method on `BndEditModel.getLastChangedAt()`. This persisted until I cleaned and rebuilt the workspace. This indicates a bug in the dependencies somewhere... something to keep a note of.

**Comment by chrisrueger** [comment]
> A quick note: after I merged this PR into my local repo, whenever I tried to run a resolve inside the test Eclipse instance, I was getting a `MethodNotFoundException` for the newly-added method on `BndEditModel.getLastChangedAt()`. This persisted until I cleaned and rebuilt the workspace.

Oh. Thanks @kriegfrj for letting me know. 

>  This indicates a bug in the dependencies somewhere... 

Could you maybe elaborate on that? Is adding a public method to `BndEditModel` a problem?

**Comment by pkriens** [comment]
It must be a caching issue. You can freely add methods anywhere as long as you update the package version when the package is exported.

**Comment by chrisrueger** [comment]
> update the package version

Ups, I didn't do that. I guess this is related to base-lining. I have no experience with it. 

So currently it is export.
image

And has this version:
image

So, I should have changed 
from: @Version("4.4.0")
to: @Version("4.4.1")

correct? 

Is there something where I would have noticed my oversight?

**Comment by kriegfrj** [comment]
> > update the package version
> 
> Ups, I didn't do that. I guess this is related to base-lining. I have no experience with it.
> 

You didn't need to in this case,  because I've already added some new public methods to BndEditModel since the last release so the package version has already been appropriately incremented.

> So currently it is exported. image
> 
> And has this version: image
> 
> So, I should have changed from: @Version("4.4.0") to: @Version("4.4.1")
> 
> correct?
> 

No, adding a method is a minor change. So if I hadn't already bumped it from 4.3.0 to 4.4.0, you would have had to increment it.

> Is there something where I would have noticed my oversight?

Bndtools reports the versioning error in the IDE.  In this case as the version increment was already implemented,  there was no error.  So you didn't miss anything.

**Comment by chrisrueger** [comment]
> Bndtools reports the versioning error in the IDE. In this case as the version increment was already implemented, there was no error. So you didn't miss anything.

Ahh thanks a lot for the explanation. I remembered I have seen this before, but wondered why not this time. Ok, that explains that.

**Comment by kriegfrj** [comment]
> It must be a caching issue. You can freely add methods anywhere as long as you update the package version when the package is exported.

The embedded repo sometimes causes these caching problems, no? Perhaps the fact that bndlib is in the embedded repo?

**Pull request merged**
