### PR TITLE
bndtools.core.test: Re-enable in CI build

### PR DESCRIPTION
**Pull request by bjhargrave**
Let's see if the tests are stable again.

### CODE REVIEW

**Comment by bjhargrave** [comment]
@kriegfrj I rebased on the latest updates to try again...

**Comment by bjhargrave** [comment]
> @kriegfrj I rebased on the latest updates to try again...

Interestingly, it seems to work on Linux but failed on Windows.

**Comment by kriegfrj** [comment]
> > @kriegfrj I rebased on the latest updates to try again...
> 
> Interestingly, it seems to work on Linux but failed on Windows.

There was a failure on both Linux and Windows - timed out waiting for import.

It is possible that we simply need to increase the timeout. Now that I have implemented locking on the import job, if the `FlushJob` happens to start just before the import job, the FlushJob will end up synchronously initializing the Workspace and the import job will have to wait until it is finished. That could take some time. Maybe I'll try bumping it up to 30s and see how it goes.

**Comment by kriegfrj** [comment]
> > > @kriegfrj I rebased on the latest updates to try again...
> > 
> > 
> > Interestingly, it seems to work on Linux but failed on Windows.
> 
> There was a failure on both Linux and Windows - timed out waiting for import.
> 
> It is possible that we simply need to increase the timeout. Now that I have implemented locking on the import job, if the `FlushJob` happens to start just before the import job, the FlushJob will end up synchronously initializing the Workspace and the import job will have to wait until it is finished. That could take some time. Maybe I'll try bumping it up to 30s and see how it goes.

Ok, it was more complicated that simply increasing the timeout. The timeout was happening because the call to `Central.getWorkspace()` in the import job was mutually deadlocking with some other job. Moral: it doesn't seem to be safe to call `getWorkspace()` from within a job that holds an Eclipse lock.

I have moved the call to getWorkspace() out of the Job, and I used your tip here to wait for the initialized workspace instead: https://github.com/bndtools/bnd/issues/4573#issuecomment-790944584. This seems to have stabilised this issue (ref #4579).

**Comment by bjhargrave** [comment]
Closing. See https://github.com/bndtools/bnd/pull/4579.

**Pull request closed without merging**
