### PR TITLE
Allow the separator in LocalIndexedRepo to be '-' or '_'

### PR DESCRIPTION
**Pull request by eli-jordan**
As discussed here https://github.com/bndtools/bnd/pull/1155

### CODE REVIEW

**Comment by bjhargrave** [comment]
Please modify your commit comment to include your Signed-off-by.

**Comment by bjhargrave** [comment]
Also, I think your commit comment means to say "Allows the separator..." rather than "All the sep...".

**Comment by eli-jordan** [comment]
My bad, I fat fingered that one.. fixed now.

**Comment by bjhargrave** [comment]
LGTM

**Pull request merged**
