### PR TITLE
[launchpad] Launchpad imported too much

### PR DESCRIPTION
**Pull request by pkriens**
Included OSGiHeaders but this included too many
dependencies and these were not even properly 
conditionally included.

Created a simple Parameters class that assumes the
header is correct and does not try to analyze 
what might be wrong.

Signed-off-by: Peter Kriens <Peter.Kriens@aqute.biz>

### CODE REVIEW

**Comment by pkriens** [comment]
@bjhargrave any change you can cherry pick this one on 4.2?

**Comment by bjhargrave** [comment]
> @bjhargrave any change you can cherry pick this one on 4.2?

Seems like this change is still not complete/finished? You have an empty enum class Mode. Why?

**Comment by pkriens** [comment]
That is a left over, I can remove that.

**Comment by bjhargrave** [comment]
Also, you add the `~` for duplicate keys but don't provide the related helper method to check if a key is duplicate and to remove the duplicate marker.

**Comment by bjhargrave** [comment]
Since launchpad is still basically in beta, how important is it to make changes for 4.2?

**Comment by pkriens** [comment]
Not crucial but extremely convenient. Both my customers start to use it in anger. Due to always having bndlib on the class path I'd not noticed the bndlib imports. Fr Krieg is also using it so it would be nice to have something at least working in 4.2. Since it is so far out of the main bnd code it looks pretty harmless.

**Comment by bjhargrave** [comment]
ok, I can cherry-pick over if you can please hurry up and add timeout/retry support to HttpClient? :-) The build failures due to failed Eclipse downloads is insufferable.

**Comment by pkriens** [comment]
LOL ok , that is a good excuse to not work on the documentation :-)

**Pull request merged**
