### PR TITLE
Fix for workspace error/refresh issue in Java OSGi Service wizard

### PR DESCRIPTION
**Pull request by scottslewis**
Previous to this change, the use of the Java OSGi Service Wizard would result in a *red* workspace error marker.  This was spurious and it's necessary to force refresh the bndtools Workspace so that the dependencies across the 3 create projects are refreshed.

### CODE REVIEW

**Comment by scottslewis** [comment]
@pkriens I removed the use of the UI thread for the workspace refresh.   Seems the unreliability/timing issue was being created  by using the canBeForked == true in project creation (done by superclass)

**Comment by pkriens** [comment]
That is great. However, looking a bit further I noticed that you're not locking the workspace? 

You're calling a method that absolutely needs to be `writeLocked(...)`.

We've been awful in this but a workspace can definitely cause weird errors. Sorry for not noticing this in the previous comment.

**Comment by scottslewis** [comment]
> That is great. However, looking a bit further I noticed that you're not locking the workspace?
> 
> You're calling a method that absolutely needs to be `writeLocked(...)`.
> 
> We've been awful in this but a workspace can definitely cause weird errors. Sorry for not noticing this in the previous comment.

Hi @pkriens .  Would you or someone mind just putting the appropriate code (e.g. writeLocked) in the appropriate location and merging this?   I don't have time right now to fumble around with the bndtools workspace synchronization needs.  Thanksinadvance.

**Comment by scottslewis** [comment]
@pkriens ping.   See previous message about bndtools synchronization.  I would like to get this and issue #5632 completely into main branch so that I can test snapshots in subsequent days.  When is the next release target date?

**Comment by pkriens** [comment]
I will fix it. It is quite simple, there is a lambda taking readLock and writeLock method on Workspace.

**Pull request merged**
