### PR TITLE
Small refactoring, simplification of error handling

### PR DESCRIPTION
**Pull request by scottslewis**

### CODE REVIEW

**Comment by scottslewis** [comment]
@kriegfrj FWIW...I have no idea why the build jdk17 windows-latest build is failing.  I don't believe it has anything to do with my recent additions, as everything compiles for me fine...and the failure doesn't have anything to do with my code changes afaict.

**Comment by scottslewis** [comment]
@kriegfrj - Would it be possible to get this pull request merged?   It doesn't fundamentally change anything...just adds some functionality for template-based wizards, and cleans up some variable naming, comments fixes etc.   I would like to use the snapshot build to test template-based wizards for remote services.

**Comment by kriegfrj** [comment]
> @kriegfrj - Would it be possible to get this pull request merged? It doesn't fundamentally change anything...just adds some functionality for template-based wizards, and cleans up some variable naming, comments fixes etc. I would like to use the snapshot build to test template-based wizards for remote services.

I've not had a detailed look, but from my cursory look I agree that this is not in the core Bndtools path and is a low risk to cause anyone headaches. I have merged it so that you can test it. We are not imminently heading towards a new release so only those of us who are on the bleeding edge will have to suffer the consequences (if any).

The JDK 17 failure is suspicious - it is odd that it keeps failing at the same point. It is almost as if Maven Central is slapping a download limit on us. But then, it would seem odd that it is always the Java 17 build that is failing because I don't think the builds always proceed in-order.

**Comment by scottslewis** [comment]
> > @kriegfrj - Would it be possible to get this pull request merged? It doesn't fundamentally change anything...just adds some functionality for template-based wizards, and cleans up some variable naming, comments fixes etc. I would like to use the snapshot build to test template-based wizards for remote services.
> 
> I've not had a detailed look, but from my cursory look I agree that this is not in the core Bndtools path and is a low risk to cause anyone headaches. I have merged it so that you can test it. We are not imminently heading towards a new release so only those of us who are on the bleeding edge will have to suffer the consequences (if any).

Thanks.  This won't cause anyone headaches...unless they try it :)...it's all new ui/wizard functionality.   

BTW, who maintains the 'minimal' and other 'built-in' workspace templates?   Could you please point me at the repos that are used for those templates?   I would like to make sure that those templates are up-to-date...and have the necessary support for annotation classes used by the new java service wizard...so that the service, impl, consumer all compile without any workspace config.

> 
> The JDK 17 failure is suspicious - it is odd that it keeps failing at the same point. It is almost as if Maven Central is slapping a download limit on us. But then, it would seem odd that it is always the Java 17 build that is failing because I don't think the builds always proceed in-order.

Yeah.  It doesn't even fail every time as you can see.   I can't explain it.

**Comment by kriegfrj** [comment]
> Thanks. This won't cause anyone headaches...unless they try it :)...it's all new ui/wizard functionality.
>

I agree but experience has made me wary of making statements that are quite so definitive. :smile:
 
> BTW, who maintains the 'minimal' and other 'built-in' workspace templates? Could you please point me at the repos that are used for those templates? I would like to make sure that those templates are up-to-date...and have the necessary support for annotation classes used by the new java service wizard...so that the service, impl, consumer all compile without any workspace config.
>

Each workspace template lives in its own GitHub repository under the Bndtools organisation:

* https://github.com/bndtools/workspace.tool.gradle (last edited by @pkriens in Dec 2021)
* https://github.com/bndtools/bndtools.workspace.min (last edited by @bjhargrave in June 2020)
* https://github.com/bndtools/workspace (last edited by @bjhargrave in Dec 2020)

If your change is simple enough I'm happy to have a review of it.

> > The JDK 17 failure is suspicious - it is odd that it keeps failing at the same point. It is almost as if Maven Central is slapping a download limit on us. But then, it would seem odd that it is always the Java 17 build that is failing because I don't think the builds always proceed in-order.
> 
> Yeah. It doesn't even fail every time as you can see. I can't explain it.

I had a closer look and when it happens it seemed to be happening specifically on *Windows* Java 17. Except the most recent dependabot push it happened on Java 19 ubuntu with the following error:

`Error: Exception in thread "main" java.net.UnknownHostException: repo.maven.apache.org`

Looks suspiciously like some transient network issues. If it doesn't settle in the next few days we'll have to take a closer look.

**Comment by scottslewis** [comment]
Thanks for the info on the workspace templates.  I will probably produce pull requests for any needed additions soon.

I did find a small bug in the new wizard classes and have fix.   @kriegfrj please see pr #5645

**Comment by scottslewis** [comment]
> Each workspace template lives in its own GitHub repository under the Bndtools organisation:
> 
> * https://github.com/bndtools/workspace.tool.gradle (last edited by @pkriens in Dec 2021)
> * https://github.com/bndtools/bndtools.workspace.min (last edited by @bjhargrave in June 2020)
> * https://github.com/bndtools/workspace (last edited by @bjhargrave in Dec 2020)

I've opened issue in the bndtools/workspace repo here https://github.com/bndtools/workspace/issues/17.  The change is a single line addition to cnf/central.maven file.  This is all that is needed to support the new Java OSGi Services wizard.

WRT bndtools.workspace.min:   Currently this workspace doesn't have any build.bnd and so no repos and so no maven repo (which is where the bundle annotation bundle is for https://github.com/bndtools/workspace/issues/17.

So my question about minimal is:   I'm happy to introduce a build.bnd that include a maven central repo via a new central.maven file, with a single entry (like https://github.com/bndtools/workspace/issues/17) that points to the needed bundle, but is this going to be accepted?   FWIW I think that providing a trivial central.maven is a good idea for even the minimal workspace template, but obviously it hasn't been that way up to now (minimal means MINIMAL :)
 
wrt the workspace.tool.gradle.  There is currently not even a cnf directory in that repo...and so no build.bnd/no repos/no maven repo...so I don't think the intention is to use this as a workspace template?

Thanksinadvance for any info.

**Pull request merged**
