### PR TITLE
Baseline suggests a "micro" bump when there is both a "minor" and a "removed" change

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
The `testMinorAndRemovedChange` test in this pull should fail. I added it to test https://github.com/bndtools/bnd/issues/1792.

### CODE REVIEW

**Comment by bjhargrave** [comment]
You need to amend your commits so that each commit message includes a `Signed-off-by` as required by CONTRIBUTING. Then push force your updated commits. Thanks.

**Comment by Ithildir** [comment]
Done!

**Comment by rotty3000** [comment]
It seems there's two issues:
1) the REMOVED delta is the highest however it never results in a MAJOR version change
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java#L207-L209
2) the calculated diff is ignored
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java#L212-L213

**Comment by rotty3000** [comment]
The changes have been incorporated into #1797 So I'll close this one.

**Pull request closed without merging**
