### PR TITLE
Implement meta-annotation for arbitrary manifest header generation

### PR DESCRIPTION
**Pull request by njbartlett**
Example:

```java
@BundleHeader(name = "Bundle-Activator", singleton=true)
public @interface BundleActivatorHeader {}

package org.example;
@BundleActivatorHeader
public class ExampleActivator implements BundleActivator { ... }
```

Output:

```
Bundle-Activator: org.example.ExampleActivator;

### CODE REVIEW

**Comment by timothyjward** [comment]
What are the rules for using this, and why is it needed?

There is already a standard OSGi Header annotation, but this one seems to be different...

**Comment by njbartlett** [comment]
This PR is already closed.

**Comment by timothyjward** [comment]
> This PR is already closed.

I can see that, but some work obviously went into this. It isn't clear from the PR closure whether this work is going to continue or not, and if it is then I think it would be good to understand the differences between this annotation and the standard ones. On the other hand if this work is being discarded then it obviously doesn't matter!

**Comment by njbartlett** [comment]
I didn't know about the standard `@Header` annotation, so I did all this work and now I'm embarrassed that somebody noticed... if only PRs could be deleted!

FWIW I think it would be useful if `@Header` could be used as a meta-annotation in the vein of `@RequireCapability`, and the `singleton` attribute is useful for headers like `Bundle-Activator`.

**Comment by timothyjward** [comment]
> FWIW I think it would be useful if @Header could be used as a meta-annotation in the vein of @RequireCapability, and the singleton attribute is useful for headers like Bundle-Activator.

It would also be nice to have some better options for things like classnames (Bundle-Activator is my primary use case too)

**Comment by timothyjward** [comment]
I did not know. That will save me a lot of refactoring pain!

Sent from my iPhone

On 7 Aug 2018, at 19:20, Neil Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


You know you can use the macro ${@class} in the value attribute of the @Header annotation, right? So @Header(name = Constants.BUNDLE_ACTIVATOR, value = "${@class}") works for an activator, just not as clean as a plain @BundleActivatorHeader.

**Comment by njbartlett** [comment]
:-)

The other macros are `@class-simple`, `@package` and `@version`. You can
see the code for these in `AnnotationHeaders.add`.

**Pull request closed without merging**
