### PR TITLE
Always setup cwd as same as project base

### PR DESCRIPTION
**Pull request by gamerson**
Better fix for setting projectLauncher.cwd == project.base

See discussion at https://github.com/bndtools/bndtools/pull/982

### CODE REVIEW

**Comment by gamerson** [comment]
@bjhargrave Can this be considered for 2.4.1?

**Comment by bjhargrave** [comment]
We first need to accept into master. We can discuss bringing into 2.4.1 at the dev call on Friday.

**Comment by gamerson** [comment]
Thanks I would like to push for this one to be inclusion because this bug
causes a jvm deadlock over on bndtools side
<https://github.com/bndtools/bndtools/pull/982> and no workarounds that I
know of.  Actually there is a workaround but it involves renaming project
configuration files that are not obvious.

On Tue, Jan 6, 2015 at 9:52 AM, BJ Hargrave <notifications@github.com>
wrote:

> We first need to accept into master. We can discuss bringing into 2.4.1 at
> the dev call on Friday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/pull/746#issuecomment-68814688>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by bjhargrave** [comment]
We will take this in to 2.4.1.

**Pull request merged**
