### PR TITLE
bnd-resolver-maven-plugin failure output has regressed

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
I know that ideally this should be fixed in Bndrun, and we discussed this on at least one call and it was going to be fixed but never was. This late stage I just want a fix for 4.3.0 that will make maven usage user friendly again.

**Comment by bjhargrave** [comment]
> This late stage I just want a fix for 4.3.0 that will make maven usage user friendly again.

I think the gradle resolve task will have the same problem. So it would be better to make a new `resolveCLI` method in Bndrun for the CLI (maven/gradle) plugins to both use when resolving.

**Comment by rotty3000** [comment]
@bjhargrave see updated.

**Comment by bjhargrave** [comment]
replaced by #3429

**Pull request closed without merging**
