### PR TITLE
Enable Maven-ArtifactId attribute (along with Maven-GroupId) to custo…

### PR DESCRIPTION
**Pull request by mrulli**
…mize maven coordinates on publish

Signed-off-by: matteo rulli <matteo.rulli@flairbit.io>

### CODE REVIEW

**Comment by mrulli** [comment]
We need to customize both the artifact id and the group id associated with the bundle when we release them in nexus through aether plugin. This pull request enables this possibility: I just added the new Maven-ArtifactId attribute along with the existing Maven-GroupId one.

**Comment by bjhargrave** [comment]
You know the aether repo plugin is deprecated and replaced by the new maven bnd repo plugin? https://github.com/bndtools/bnd/wiki/Changes-in-3.2.0#maven-repository-support

**Comment by mrulli** [comment]
No I did't: we'll migrate to the new MavenBndRepository plugin as soon as we upgrade to bnd 3.2.0. Thanks.

**Comment by bjhargrave** [comment]
So we can close this PR?

**Comment by mrulli** [comment]
Yes: if I understood correctly the docs, the -pom directive will provide the same capability with the new plugin.

**Pull request closed without merging**
