### PR TITLE
consistent formatting only, because I was annoyed

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
fix stray asm reference

**Comment by pkriens** [comment]
Wouldn't it be easier and better for the future to invest this time in a formatter? A formatter should not be hard to make looking at the BndEditModel? Imho would also be more fun?

Then we could also sort he headers, instructions, and macros ...

**Comment by rotty3000** [comment]
I do agree it would be nice. @pkriens  you ok with this small change however?

**Comment by pkriens** [comment]
Yup, no problem ... just find it not so interesting since the first edit usually mucks it up again.

**Comment by rotty3000** [comment]
@pkriens I tend to use a small eclipse plugin called AnyEdit which does do these types of whitespace corrections for me automatically. What usually ends up happening in projects where I collaborate with others is that I back whitespace changes out of commits so that real code changes are always the centre point. Or I end up disabling this whitespace plugin in specific projects :) (like bnd)

**Comment by pkriens** [comment]
Ah well, just need a volunteer. I think it is actually surprisingly easy since the BndEditModel already contains all the info.

**Pull request merged**
