### PR TITLE
[launcher] Support -executable location format

### PR DESCRIPTION
**Pull request by pkriens**
This fix was added to the 5.1 master but had
API changes. This is similar without the API
changes.

basically allows a -executable: location='${@bsn}'
instruction to set the format of the path used
in the launcher executable jar. The default 
path can contain versions and since the path
is used for the OSGi location, new bundles
are created then the path changes. So you get
the same bsn installed several times. Not good

Signed-off-by: Peter Kriens <Peter.Kriens@aqute.biz>

### CODE REVIEW

**Comment by bjhargrave** [comment]
We will also need to add a bullet to https://github.com/bndtools/bnd/wiki/Changes-in-5.0.1#fixes-since-500 describing this fix.

**Comment by pkriens** [comment]
done

**Comment by pkriens** [comment]
will you merge or do I

**Comment by bjhargrave** [comment]
> will you merge or do I

I can do it since I also need to tag it RC2.

**Comment by bjhargrave** [comment]
Fixes #3810 for 5.0.1 release.

**Pull request merged**
