### PR TITLE
maven: Remove eclipse warnings

### PR DESCRIPTION
**Pull request by bjhargrave**

### CODE REVIEW

**Comment by maggu2810** [comment]
I am pretty sure I created a PR with that change today but cannot find it anymore.
Has it been deleted?

**Comment by bjhargrave** [comment]
> I am pretty sure I created a PR with that change today but cannot find it anymore.
> Has it been deleted?

I never saw such a PR.

**Comment by maggu2810** [comment]
Okay, then I forget to submit it:
https://github.com/maggu2810/bnd/commit/638aac79f823298530214a0ac187e10e4ded3ba3

Sorry for that warnings.

**Comment by bjhargrave** [comment]
> Sorry for that warnings.

No problem :-)

**Pull request merged**
