### PR TITLE
[contributions] Add description about WIP PRs

### PR DESCRIPTION
**Pull request by kriegfrj**

### CODE REVIEW

**Comment by seanbright** [comment]
Would it make more sense to create a "wip" or "work-in-progress" label?

**Comment by kriegfrj** [comment]
Possibly - I just documented the process as it currently is. :smile:

**Comment by bjhargrave** [comment]
> Would it make more sense to create a "wip" or "work-in-progress" label?

Maybe, but WIP in the PR title is pretty common and more in-your-face than some label I wont notice :-) Frankly, we do not use labels very consistently or at all in this project.

**Comment by kriegfrj** [comment]
Also, labels can only be added/removed by the project maintainers, which means the author of the PR may not be able to change it.

**Pull request merged**
