### PR TITLE
Add support for building multi-release jars (automatic!)

### LINKED ISSUE #5346: [bnd] Support processing of Multi-Release-Jars
This is related to 
- https://github.com/bndtools/bnd/issues/2227

But only handles a subset, that is, support processing of Multi-Release-Jars.

Currently when one tries to process a Multi-Release-Jar with BND, the `bnd-maven-plugin` complains with the following message:
> [ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:6.4.0-SNAPSHOT:bnd-process (bnd-process) on project clickhouse-client: Classes found in the wrong directory: {META-INF/versions/9/module-info.class=module-info}

The problem is, that BND currently do not read Multi-Release-Jar  correctly leading to issues else where
- https://github.com/bndtools/bnd/issues/5334
- https://github.com/bndtools/bnd/issues/5327
-  ... (see linked issues of https://github.com/bndtools/bnd/issues/2227)

One problem is, that Multi-Release-Jar processing requires to know what are the java release, this usually is taken from either the running VM or by specify it directly, e.g by a compiler switch.

Therefore I propose, as a first step, to allow specify a new directive in a bnd file `-release` that takes an integer and is interpreted as the desired target release.

BND should then work in the following way:

- if no `-release` is specified, it should behave as of today, e.g. Multi-Release-Jars processing is disabled and might even lead to the current problems
- if `-release` is specified and it is smaller than `0` it is interpreted as if it was not specified
- if `-release` is specified and it is smaller than `9` it is interpreted as processing a jar with the default jar content that is ignoring anything from `META-INF/versions` and thus also don't find any modules info, or classes and do not complain
- if `-release` is specified and it is larger or equal to `9` then it is interpreted as processing a jar with the given release, that is any class/resource in `META-INF/versions/...` that are smaller or equal to `<release>` will shade any class/resource from the default jar content

This will ensure:

1. Current users of BND won't be affected and it would be 100% backward compatible
2. Users that demand Multi-Release-Jar can at least read and process jars with the desired `release` option

### PR DESCRIPTION
**Pull request by laeubi**
This is based on:

- https://github.com/bndtools/bnd/pull/5357

so to see the actual changes from this PR simply select the last commit on the review tab.

an allows to specify 
`Multi-Release: true`
in a BND file to instruct BND building an [OSGi Multi-Release Bundle](https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-multireleasejar) based on the detected versions.

@timothyjward this also includes fixing general processing of BND in cases where multi-release is off, and methods for `Jar` to put versioned resources / supplemental manifests. If you think it helps, both aspects could be split into separate PRs as well.

This will fix #5346

### CODE REVIEW

**Comment by laeubi** [comment]
I have adjusted [the example here](https://github.com/ClickHouse/clickhouse-jdbc/blob/ce23675513519a6dc8efdfe9adbb91bba19c8f01/pom.xml#L599) to reflect the changes, the
[clickhouse-http-client-0.3.3-SNAPSHOT.jar.zip](https://github.com/bndtools/bnd/files/9421835/clickhouse-http-client-0.3.3-SNAPSHOT.jar.zip) shows the result for such a bundle build by bnd with supplemental manifests for version 9 and 11.

**Comment by timothyjward** [comment]
I think the direction here is good. We probably need some more multi-release bundle generation tests before it can be merged though. 
One feature that seems likely to have issues is the generation of `java.*` imports for multi release manifests at versions greater than 11.

**Comment by laeubi** [comment]
> We probably need some more multi-release bundle generation tests before it can be merged though.

Can you suggest a test-case that might be adapted for this purpose?

> One feature that seems likely to have issues is the generation of `java.*` imports for multi release manifests at versions greater than 11.

According to my tests (see attached generated bundle) it simply "works", e.g. I see `java.*` imports for the java 11 variant.

**Comment by laeubi** [comment]
> We probably need some more multi-release bundle generation tests before it can be merged though.

I have added now a test here:
https://github.com/bndtools/bnd/blob/51a4947c7473e6dbfa56d2e37e1b08575b652d6b/biz.aQute.bndlib.tests/test/aQute/bnd/osgi/AnalyzerTest.java#L24-L53

**Pull request closed without merging**
