### PR TITLE
Lookup maven's local repository instead of assuming ~/.m2/repository

### LINKED ISSUE #1685: [3.3.0 RC1] MavenRepository not using localRepository from settings / cannot follow symlink
In our corporate environment we set our local-maven-repo to another location than ~/.m2/repository due to performance issues with the virus-scanner. 
The location is configured in Mavens settings.xml:
`<localRepository>C:/Development/temp/maven-local-repository</localRepository>`
Since some tools still use the default location I've also setup a symlink (Windows mklink) which also points to the configured location (this usually works).

Now BndTools is able to download the maven-artifacts I specify to the configured local-repo and the Repositories-View is able to open the file, but using the artifact as build-dependency yields the following exception.

`java.lang.reflect.InvocationTargetException
	at org.osgi.util.promise.PromiseImpl.getValue(PromiseImpl.java:159)
	at aQute.bnd.repository.maven.provider.MavenBndRepository.get(MavenBndRepository.java:390)
	at bndtools.model.repo.RepositoryEntry.getFile(RepositoryEntry.java:117)
	at bndtools.views.repository.RepositoriesView$7$1.run(RepositoriesView.java:372)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.FileNotFoundException: For Maven artifact org.ops4j.pax.cdi:pax-cdi-api:1.0.0-SNAPSHOT,
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Root exception:
java.io.FileNotFoundException: For Maven artifact org.ops4j.pax.cdi:pax-cdi-api:1.0.0-SNAPSHOT,
	at aQute.maven.provider.MavenRepository$1.run(MavenRepository.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

The error-log complains about the missing file, which actually exists on the filesystem.

Bnd should either honor the repository-location specified within the settings, or make sure to follow symlinks.

### PR DESCRIPTION
**Pull request by seanbright**
Fixes #1685

Signed-off-by: Sean Bright <sean.bright@gmail.com>

### CODE REVIEW

**Comment by seanbright** [comment]
@bjhargrave @pkriens any objection to merging this?

**Comment by bjhargrave** [comment]
> any objection to merging this?

Yes, I think. (Next comment will detail my concerns.)

**Comment by bjhargrave** [comment]
See <http://bnd.bndtools.org/instructions/connection-settings.html>. Bnd allows `-connection-settings` to specific the file to read. If not specified it then looks for `~/.bnd/settings.xml` and finally reads `~/.m2/settings.xml`. Bnd uses the file only for connection settings.

This PR (1) expands to read just one more piece of information but (2) fails to look in the other files Bnd uses.

So I think this PR is wrong. A user can use the Maven standard was of the system property `maven.repo.local` to change the default location of the local repo if needed.

**Comment by seanbright** [comment]
OK

**Pull request closed without merging**
