### PR TITLE
Remove unnecessary promise and function bundles

### LINKED ISSUE #5787: Remove org.osgi.util.promise from bndtools.main.feature
The `org.osgi.util.promise` has been included in the Eclipse platform since 2022-06.  Can we remove the older version included in `bndtools.main` feature?

https://github.com/bndtools/bnd/blob/99e901cda3a445cdb241ded80d66b3c76ec6a284/org.bndtools.p2/features/bndtools.main/feature.xml#L685-L690

### PR DESCRIPTION
**Pull request by tjwatson**
Fixes #5787

### CODE REVIEW

**Comment by kriegfrj** [comment]
LGTM, but it would be best to test it on a fresh Eclipse installation.

**Comment by pkriens** [comment]
@kriegfrj its the snapshot so we can run a bit of risk,just lets see how this goes and correct if it goes wrong.

**Comment by kriegfrj** [comment]
> @kriegfrj its the snapshot so we can run a bit of risk,just lets see how this goes and correct if it goes wrong.

No problem, just a long as one of us remembers to test with a fresh install before the next release. While we work with the snapshots,  typically we are upgrading an existing installation rather than installing afresh. I have a feeling the problems with this PR (if there are any) will be most likely to manifest in a fresh install rather than an upgrade.

**Comment by pkriens** [comment]
You're right. However, I tend to install bndtools in fresh Eclipse releases so it should show up and I have strong faith in Thomas Watson :-)

**Comment by tjwatson** [comment]
> You're right. However, I tend to install bndtools in fresh Eclipse releases so it should show up and I have strong faith in Thomas Watson :-)

Thanks for the show of confidence in me :)

FWIW I did test my local build of BND tools into a fresh install of the Eclipse Project I-Build from yesterday (https://download.eclipse.org/eclipse/downloads/drops4/I20231011-1800/) and it worked fine.

**Pull request merged**
